[AUTO] luna:2.1.5:HLC:k8s:dotfiles-updater:1bf6648d3343

diff --git a/config/bin-hpc/vnc-ctl b/config/bin-hpc/vnc-ctl
--- a/config/bin-hpc/vnc-ctl
+++ b/config/bin-hpc/vnc-ctl
@@ -8,23 +8,22 @@ set -o pipefail
 # Script Constants
 readonly CURDIR="$(cd -P -- "$(dirname -- "")" && pwd -P)"
 readonly SCRIPT="$(basename "$0")"
+# Default log level (debug logs are disabled)
+LOG_LVL=0
 
 # Handle Signals
 # trap ctrl-c and SIGTERM
 trap ctrl_c_signal_handler INT
 trap term_signal_handler SIGTERM
 
-function ctrl_c_signal_handler()
-{
+function ctrl_c_signal_handler() {
   log_error "User Interrupt! CTRL-C"
   exit 4
 }
-function term_signal_handler()
-{
+function term_signal_handler() {
   log_error "Signal Interrupt! SIGTERM"
   exit 4
 }
-
 
 #>> diana::snippet:bash-logger:begin <<#
 # shellcheck shell=bash
@@ -257,38 +256,9 @@ function log_step_variable()
 }
 #>> diana::snippet:bash-logger:end <<#
 
-
-
-function get_abspath()
-{
-  # Generate absolute path from relative path
-  # ARGUMENTS:
-  # $1     : relative filename
-  if [ -d "$1" ]; then
-    # dir
-    (
-      cd "$1" || return
-      pwd
-    )
-  elif [ -f "$1" ]; then
-    # file
-    if [[ $1 = /* ]]; then
-      printf "%s" "$1"
-    elif [[ $1 == */* ]]; then
-      printf "%s" "$(
-        cd "${1%/*}" || return
-        pwd
-      )/${1##*/}"
-    else
-      printf "%s" "$(pwd)/$1"
-    fi
-  fi
-}
-
 # Checks if command is available
-function has_command()
-{
-  if command -v "$1" > /dev/null; then
+function has_command() {
+  if command -v "$1" >/dev/null; then
     return 0
   else
     return 1
@@ -296,164 +266,226 @@ function has_command()
   return 1
 }
 
-function display_usage()
-{
-  #Prints out help menu
-  cat << EOF
-Bash script to run shellcheck usng docker on files specified.
 
-Usage: ${TEAL}${SCRIPT} ${BLUE} [options] ${NC}
-${VIOLET}
-------------------------- Arguments ----------------------------${NC}
-List of Files to run shellcheck on
-${ORANGE}
----------------- Options with Required Argments-----------------${NC}
-None
-${GRAY}
---------------------- Debugging & Help -------------------------${NC}
-[-d | --debug]          Enable debug loggging
-[--stderr]              Log to stderr instead of stdout
-[-h | --help]           Display this help message${NC}
-${TEAL}
-------------------- Environment Variables ----------------------${NC}
-${BLUE}LOG_TO_STDERR${NC}     - Set this to 'true' to log to stderr.
-${BLUE}NO_COLOR${NC}          - Set this to NON-EMPTY to disable all colors.
-${BLUE}CLICOLOR_FORCE${NC}    - Set this to NON-ZERO to force colored output.
-                    Other color related conditions are ignored.
-                  - Colors are disabled if output is not a TTY
-EOF
+
+function run_vnc()
+{
+  # Because modules sometimes do not load variables into shell
+  load_modules
+
+  if [[ -d $HOME/.vnc ]]; then
+    log_debug ".vnc directory exists!"
+  else
+    log_info "Creating ~/.vnc"
+    if mkdir -p "$HOME/.vnc"; then
+      log_success "OK"
+    else
+      log_error "Failed to create logs and config folder ~/.vnc"
+      exit 1
+    fi
+  fi
+
+  if has_command vncserver; then
+
+    # Use better res, auto kill and start xfce scession properly
+    if [[ $disable_autokill == "true" ]]; then
+      AUTOKILL=""
+    else
+      AUTOKILL="-autokill"
+    fi
+
+    if [[ $enable_vgl == "true" ]]; then
+      TVNC_VGL=1
+    else
+      TVNC_VGL=0
+    fi
+    log_info "Starting new VNC sesion"
+    TVNC_VGL="${TVNC_VGL}" "${TURBOVNC_DIR}/bin/vncserver" \
+      "${AUTOKILL}" \
+      -geometry "${WM_RESOLUTION}" \
+      -fp "${HOME}/.local/share/fonts" \
+      -log "${HOME}/.vnc/vncserver.log" \
+      -wm "startxfce4" &> /dev/null
+    exit_code="$?"
+    if [[ $exit_code -ne 0 ]]; then
+      log_error "something went wrong while running vnc server."
+      exit "${exit_code}"
+    else
+      log_success "Successfully started VNC server."
+      log_success "To see how to connect to it run the script with --info"
+    fi
+  else
+    log_error "Cannot find vncserver command! Allow the script to load modules!"
+    exit 1
+  fi
 }
 
-function parse_options()
+function load_modules()
 {
-  NON_OPTION_ARGS=()
-  while [[ ${1} != "" ]]; do
-    case ${1} in
-      --stderr) LOG_TO_STDERR="true" ;;
-      -v | --verbose)
-        LOG_LVL="0"
-        log_debug "Enabled verbose logging"
-        ;;
-      -h | --help)
-        display_usage
-        exit 0
-        ;;
-      *) NON_OPTION_ARGS+=("${1}") ;;
-    esac
-    shift
-  done
+  if [[ $load_required_modeule == "false" ]]; then
+    log_warning "Skipped loading Modules!!"
+  else
+    log_info "Loading Latest VNC module"
+    # Cant avoid eval here
+    eval module load tools/turbovnc/latest &> /dev/null
+  fi
+}
+
+function vnc_kill()
+{
+  local displays
+
+  load_modules
+  #shellcheck disable=SC2009
+  displays="$(ps -ef | grep "$USER" | grep '[X]vnc' | awk '{print $9}' | tr -d :)"
+
+  if [ -n "$displays" ]; then
+    #shellcheck disable=SC2116
+    for d in $(echo "$displays"); do
+      log_debug "Stopping vnc server on display:$d"
+      read -rp "Do you want to stop vncserver :${d} (y/N) " yesno
+      #Needed because bash on nemo is too old
+      #shellcheck disable=SC2019,SC2018
+      ans=$(echo "${yesno}" | tr "A-Z" "a-z")
+      if [[ ${ans} == "y" ]];then
+        "${TURBOVNC_DIR}"/bin/vncserver -kill ":${d}"
+      fi
+    done
+  else
+    log_error "No running servers were detected!"
+  fi
+}
+
+
+function display_info()
+{
+  node_name=$(hostname)
+  connection_count="$(pgrep -a -u "$USER" [X]vnc | awk '{print $3}' | tr -d : | wc -l)"
+  if [[ connection_count -gt 0 ]];then
+    log_success "There are ${connection_count} active sessions"
+
+    # for file in ${HOME}/.vnc/${node_name}\:*.pid; do
+    while read -p -r line; do
+      port=$((5900+line))
+      vnc_ports+=("$port")
+    done < <(pgrep -a -u "$USER" [X]vnc | awk '{print $3}' | tr -d : )
+
+    echo ""
+    echo "Linux"
+    echo "--------------------"
+    for p in "${vnc_ports[@]}"; do
+      echo "* ssh -fCNL ${p}:${node_name}:${p} ${USER}@login.nemo.uni-freiburg.de"
+    done
+    echo ""
+    echo "Windows PuTTY"
+    echo "--------------------"
+    echo "Start another Putty session and navigate to Connection -> SSH -> Tunnels"
+    for p in "${vnc_ports[@]}"; do
+      echo "* Source Port: ${p} Destination: ${node_name}:${p}"
+    done
+
+    echo ""
+    echo "VNC Viewer Address(s)"
+    echo "-------------------------"
+    for p in "${vnc_ports[@]}"; do
+      echo "* localhost:${p}"
+    done
+    echo ""
+    echo "Tips"
+    echo "-----------"
+    echo "These addresses are only active after you complete Linux/Windows specific steps/commands above."
+    echo "To kill the sessions, "
+    echo "  * logout (if you did not disable autokill)"
+    echo "  * use vnc-session --kill command."
+  else
+    log_error "There are no active VNC sessions on this node!"
+  fi
+}
+
+function display_usage()
+{
+#Prints out help menu
+cat <<EOF
+Handy utility to run VNC server.
+
+Usage: ${GREEN}${SCRIPT} ${BLUE}  [options]${NC}
+---------------------------------------------
+[-r --resolution]        Geometry Params (default=1920x1080)
+[-i --info]              Display connection info]
+[-k --kill]              Kill all running VNC sessions
+[-a --disable-autokill]  Disables passing -autokill to vnc module.
+                          This has a side effect of not killing the
+                          server, even when you click logout.
+                          Use with caution.
+[-m --skip-load]         Skip Loading modules
+[-v --enable-vgl]        Enables vgl.
+[-h --help]              Display this help message]
+
+Notes on resolution parameter
+----------------------------------
+Resolution MUST be of format
+
+a) W0xH0+X0+Y0[,W1xH1+X1+Y1,...,WnxHn+Xn+Yn]
+  Set multi-screen  geometry  of  the virtual X display.
+  Wi and Hi are the width and height of Screen i, and Xi and Yi.
+  specify the offset of Screen i relative to the origin.
+  The total width and height are determined by the bounding box of all screens.
+b) widthxheight
+  Set width and height of the virtual X display.
+
+Author : Prasad Tengse <prasad.tengse@venus.uni-freiburg.de>
+VCS    : https://github.com/imtek-emp/hpc-dotfiles.git
+EOF
 }
 
 function main()
 {
-  parse_options "$@"
 
-  if has_command docker; then
-    log_debug "Docker cli exists!"
-  else
-    log_error "Docker not found!"
-    log_error "This script uses docker to ensure consistancy in CI/CD systems"
-    log_error "Please install docker and try again"
-    exit 1
-  fi
+  run_mode="run"
+  WM_RESOLUTION="1920x1080"
 
-  # Check if shellcheck version should be changed?
-  if [[ -n $SHELLCHECK_VERSION ]]; then
-    declare -r SHELLCHECK_VERSION_REGEX="^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\$"
-    if [[ ! $SHELLCHECK_VERSION =~ ^v ]]; then
-      log_debug "Shellcheck version specified does not start with prefix v, append it"
-      SHELLCHECK_VERSION="v${SHELLCHECK_VERSION}"
-    fi
 
-    if [[ $SHELLCHECK_VERSION =~ $SHELLCHECK_VERSION_REGEX ]]; then
-      log_debug "Shellcheck version is valid"
-    else
-      log_error "Invalid shellcheck version"
-      log_error "Version specified must match regex: ${SHELLCHECK_VERSION_REGEX}"
-      exit 1
-    fi
-  else
-    SHELLCHECK_VERSION="v0.7.2"
-  fi
-
-  log_notice "Using shellcheck version tag: ${SHELLCHECK_VERSION}"
-
-  # check if docker image is available
-  if docker inspect "koalaman/shellcheck:${SHELLCHECK_VERSION}" > /dev/null 2>&1; then
-    log_debug "Using existing image - koalaman/shellcheck:${SHELLCHECK_VERSION}"
-  else
-    log_info "Pull docker image: koalaman/shellcheck:${SHELLCHECK_VERSION} "
-    if docker pull koalaman/shellcheck:${SHELLCHECK_VERSION}; then
-      log_success "Pull OK"
-    else
-      log_error "Shellcheck image specified is not present on local system"
-      log_error "or on dockerhub. No image - koalaman/shellcheck:${SHELLCHECK_VERSION}"
-      exit 1
-    fi
-  fi
-
-  declare -ga SHELLCHECK_FILES
-  declare -ga SHELLCHECK_ERRORS
-  declare abs_file_path
-
-  # Loop over non option arguments and check if the files are
-  # present and are readable
-  for file in "${NON_OPTION_ARGS[@]}"; do
-    abs_file_path=""
-    # absolute path takes priority
-    if [[ -r ${file} ]]; then
-      log_debug "Readable file: ${file}"
-      abs_file_path="$(get_abspath "${file}")"
-    # search in REPO_ROOT if REPO_ROOT is defined
-    elif [[ -r ${REPO_ROOT}/${file} ]] && [[ -n ${REPO_ROOT} ]]; then
-      log_debug "Readable file: ${REPO_ROOT}/${file} (REPO_ROOT)"
-      abs_file_path="$(get_abspath "${REPO_ROOT}/${file}")"
-    else
-      log_error "File not found : ${file}"
-    fi
-
-    if [[ -n ${abs_file_path} ]]; then
-      log_debug "Adding ${abs_file_path} to file list"
-      SHELLCHECK_FILES+=("${abs_file_path}")
-    fi
+  while [ "${1}" != "" ]; do
+    case ${1} in
+      -r | --resolution )       shift;WM_RESOLUTION="${1}";
+                                ;;
+      -g | --enable-vgl)        enable_vgl="true";
+                                ;;
+      -a | --disable-autokill)  disable_autokill="true";
+                                ;;
+      -i | --info)              run_mode="info";
+                                ;;
+      -k | --kill)              run_mode="kill";
+                                ;;
+      -m | --skip-load)         load_required_modeule="false";
+                                ;;
+      # Debugging options
+      --stderr)                 LOG_TO_STDERR="true";;
+      -v | --verbose)           LOG_LVL="1";
+                                log_info "Enable verbose logging";;
+      -h | --help )             display_usage;exit 0;;
+      * )                       log_error "Invalid argument(s). See usage below.";
+                                usage; exit 1;;
+    esac
+    shift
   done
 
-  if [[ ${#SHELLCHECK_FILES[@]} -eq 0 ]]; then
-    log_error "No files to shellcheck!"
+  if [[ -z $WM_RESOLUTION ]]; then
+    log_error "WM_RESOLUTION is undefined!"
     exit 1
   else
-    local res
-    # Use shellcheck docker image for consistancy
-    for file in "${SHELLCHECK_FILES[@]}"; do
-      file_basename="$(basename "${file}")"
-      log_info "$file"
-      docker run \
-        --rm \
-        --workdir=/app/ \
-        --network=none \
-        -v "${file}:/app/${file_basename}:ro" \
-        koalaman/shellcheck:"${SHELLCHECK_VERSION}" \
-        --color=always \
-        "/app/${file_basename}"
-      res="$?"
-      if [[ $res -eq 0 ]]; then
-        log_success "OK"
-      else
-        SHELLCHECK_ERRORS+=("${file}")
-        log_error "FAILED"
-      fi
-    done
+    log_debug "Setting geometry params to $WM_RESOLUTION"
   fi
 
-  if [ ${#SHELLCHECK_ERRORS[@]} -eq 0 ]; then
-    log_notice "Hooray! All files passed shellcheck."
-  else
-    log_error "${#SHELLCHECK_ERRORS[*]} file(s) failed shellcheck: ${SHELLCHECK_ERRORS[*]}"
-    exit 1
-  fi
+  # Run
+  case "${run_mode}" in
+    run)        run_vnc;;
+    kill)       vnc_kill;;
+    info)       display_info;exit $?;;
+    *)          log_error "Internal Error! Invalid mode!";exit 1;;
+  esac
+
+
 }
 
 main "$@"
-
-# diana:{diana_urn_flavor}:{remote}:{source}:{version}:{remote_path}:{type}
-# diana:2:github:tprasadtp/templates::scripts/shellcheck.sh:static
