[AUTO] luna:2.1.5:HLC:k8s:dotfiles-updater:b1a94ee92d8b

diff --git a/config/bin-hpc/vnc-session b/config/bin-hpc/vnc-session
--- a/config/bin-hpc/vnc-session
+++ b/config/bin-hpc/vnc-session
@@ -35,45 +35,44 @@ function term_signal_handler() {
 # automatically updated and all changes between markers wil be ignored.
 
 # Logger core
-__logger_core_event_handler()
-{
+__logger_core_event_handler() {
   [ "$#" -lt 2 ] && return
 
   # Caller is same as level name
   local lvl_caller="${1:-info}"
 
   case $lvl_caller in
-    log_trace | trace)
-      lvl_caller="trace"
-      level="0"
-      ;;
-    log_debug | debug)
-      lvl_caller="debug"
-      level="10"
-      ;;
-    log_info | info)
-      lvl_caller="info"
-      level="20"
-      ;;
-    log_success | success | ok)
-      lvl_caller="success"
-      level="20"
-      ;;
-    log_warning | warning | warn)
-      lvl_caller="warning"
-      level="30"
-      ;;
-    log_notice | notice)
-      lvl_caller="notice"
-      level="35"
-      ;;
-    log_error | error)
-      lvl_caller="error"
-      level="40"
-      ;;
-    *)
-      level="40"
-      ;;
+  log_trace | trace)
+    lvl_caller="trace"
+    level="0"
+    ;;
+  log_debug | debug)
+    lvl_caller="debug"
+    level="10"
+    ;;
+  log_info | info)
+    lvl_caller="info"
+    level="20"
+    ;;
+  log_success | success | ok)
+    lvl_caller="success"
+    level="20"
+    ;;
+  log_warning | warning | warn)
+    lvl_caller="warning"
+    level="30"
+    ;;
+  log_notice | notice)
+    lvl_caller="notice"
+    level="35"
+    ;;
+  log_error | error)
+    lvl_caller="error"
+    level="40"
+    ;;
+  *)
+    level="40"
+    ;;
   esac
 
   # Immediately return if log level is not enabled
@@ -134,54 +133,54 @@ __logger_core_event_handler()
   # However, if LOG_FMT is set to "full" or "long" or if colors are disabled,
   # we will enable long format with timestamps
   case "$lvl_caller" in
-    trace)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[TRACE ]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [TRACE ]"
-      # shellcheck disable=SC2155
-      [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;246m')"
-      ;;
-    debug)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[DEBUG ]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [DEBUG ]"
-      # shellcheck disable=SC2155
-      [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;250m')"
-      ;;
-    info)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[INFO  ]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [INFO  ]"
-      # Avoid printing color reset sequence as this level is not colored
-      [ "$lvl_colorized" = "true" ] && lvl_color_reset=""
-      ;;
-    success)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[OK    ]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [OK    ]"
-      # shellcheck disable=SC2155
-      [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;83m')"
-      ;;
-    warning)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[WARN  ]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [WARN  ]"
-      # shellcheck disable=SC2155
-      [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;214m')"
-      ;;
-    notice)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[NOTICE]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [NOTICE]"
-      # shellcheck disable=SC2155
-      [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;81m')"
-      ;;
-    error)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[ERROR ]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [ERROR ]"
-      # shellcheck disable=SC2155
-      [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;197m')"
-      ;;
-    *)
-      [ "$lvl_prefix" = "name" ] && local lvl_string="[UNKOWN]"
-      [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [UNKNOWN]"
-      # Avoid printing color reset sequence as this level is not colored
-      [ "$lvl_colorized" = "true" ] && lvl_color_reset=""
-      ;;
+  trace)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[TRACE ]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [TRACE ]"
+    # shellcheck disable=SC2155
+    [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;246m')"
+    ;;
+  debug)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[DEBUG ]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [DEBUG ]"
+    # shellcheck disable=SC2155
+    [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;250m')"
+    ;;
+  info)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[INFO  ]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [INFO  ]"
+    # Avoid printing color reset sequence as this level is not colored
+    [ "$lvl_colorized" = "true" ] && lvl_color_reset=""
+    ;;
+  success)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[OK    ]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [OK    ]"
+    # shellcheck disable=SC2155
+    [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;83m')"
+    ;;
+  warning)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[WARN  ]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [WARN  ]"
+    # shellcheck disable=SC2155
+    [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;214m')"
+    ;;
+  notice)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[NOTICE]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [NOTICE]"
+    # shellcheck disable=SC2155
+    [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;81m')"
+    ;;
+  error)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[ERROR ]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [ERROR ]"
+    # shellcheck disable=SC2155
+    [ "$lvl_colorized" = "true" ] && local lvl_color="$(printf '\e[38;5;197m')"
+    ;;
+  *)
+    [ "$lvl_prefix" = "name" ] && local lvl_string="[UNKOWN]"
+    [ "$lvl_prefix" = "name+ts" ] && local lvl_string="$lvl_ts [UNKNOWN]"
+    # Avoid printing color reset sequence as this level is not colored
+    [ "$lvl_colorized" = "true" ] && lvl_color_reset=""
+    ;;
   esac
 
   if [ "${LOG_TO_STDERR:-false}" = "true" ]; then
@@ -192,43 +191,35 @@ __logger_core_event_handler()
 }
 
 # Leveled Loggers
-log_trace()
-{
+log_trace() {
   __logger_core_event_handler "trace" "$@"
 }
 
-log_debug()
-{
+log_debug() {
   __logger_core_event_handler "debug" "$@"
 }
 
-log_info()
-{
+log_info() {
   __logger_core_event_handler "info" "$@"
 }
 
-log_success()
-{
+log_success() {
   __logger_core_event_handler "ok" "$@"
 }
 
-log_warning()
-{
+log_warning() {
   __logger_core_event_handler "warn" "$@"
 }
 
-log_warn()
-{
+log_warn() {
   __logger_core_event_handler "warn" "$@"
 }
 
-log_notice()
-{
+log_notice() {
   __logger_core_event_handler "notice" "$@"
 }
 
-log_error()
-{
+log_error() {
   __logger_core_event_handler "error" "$@"
 }
 #>> diana::snippet:bash-logger:end <<#
@@ -243,10 +234,7 @@ function has_command() {
   return 1
 }
 
-
-
-function run_vnc()
-{
+function run_vnc() {
   # Because modules sometimes do not load variables into shell
   load_modules
 
@@ -282,7 +270,7 @@ function run_vnc()
       -geometry "${WM_RESOLUTION}" \
       -fp "${HOME}/.local/share/fonts" \
       -log "${HOME}/.vnc/vncserver.log" \
-      -wm "startxfce4" &> /dev/null
+      -wm "startxfce4" &>/dev/null
     exit_code="$?"
     if [[ $exit_code -ne 0 ]]; then
       log_error "something went wrong while running vnc server."
@@ -297,19 +285,17 @@ function run_vnc()
   fi
 }
 
-function load_modules()
-{
+function load_modules() {
   if [[ $load_required_modeule == "false" ]]; then
     log_warning "Skipped loading Modules!!"
   else
     log_info "Loading Latest VNC module"
     # Cant avoid eval here
-    eval module load tools/turbovnc/latest &> /dev/null
+    eval module load tools/turbovnc/latest &>/dev/null
   fi
 }
 
-function vnc_kill()
-{
+function vnc_kill() {
   local displays
 
   load_modules
@@ -324,7 +310,7 @@ function vnc_kill()
       #Needed because bash on nemo is too old
       #shellcheck disable=SC2019,SC2018
       ans=$(echo "${yesno}" | tr "A-Z" "a-z")
-      if [[ ${ans} == "y" ]];then
+      if [[ ${ans} == "y" ]]; then
         "${TURBOVNC_DIR}"/bin/vncserver -kill ":${d}"
       fi
     done
@@ -333,19 +319,17 @@ function vnc_kill()
   fi
 }
 
-
-function display_info()
-{
+function display_info() {
   node_name=$(hostname)
   connection_count="$(pgrep -a -u "$USER" [X]vnc | awk '{print $3}' | tr -d : | wc -l)"
-  if [[ connection_count -gt 0 ]];then
+  if [[ connection_count -gt 0 ]]; then
     log_success "There are ${connection_count} active sessions"
 
     # for file in ${HOME}/.vnc/${node_name}\:*.pid; do
     while read -p -r line; do
-      port=$((5900+line))
+      port=$((5900 + line))
       vnc_ports+=("$port")
-    done < <(pgrep -a -u "$USER" [X]vnc | awk '{print $3}' | tr -d : )
+    done < <(pgrep -a -u "$USER" [X]vnc | awk '{print $3}' | tr -d :)
 
     echo ""
     echo "Linux"
@@ -379,10 +363,9 @@ function display_info()
   fi
 }
 
-function display_usage()
-{
-#Prints out help menu
-cat <<EOF
+function display_usage() {
+  #Prints out help menu
+  cat <<EOF
 Handy utility to run VNC server.
 
 Usage: ${GREEN}${SCRIPT} ${BLUE}  [options]${NC}
@@ -415,34 +398,52 @@ VCS    : https://github.com/imtek-emp/hpc-dotfiles.git
 EOF
 }
 
-function main()
-{
+function main() {
 
-  run_mode="run"
+  local run_mode="run"
+  local exclusive_conflicts=0
+
   WM_RESOLUTION="1920x1080"
-
 
   while [ "${1}" != "" ]; do
     case ${1} in
-      -r | --resolution )       shift;WM_RESOLUTION="${1}";
-                                ;;
-      -g | --enable-vgl)        enable_vgl="true";
-                                ;;
-      -a | --disable-autokill)  disable_autokill="true";
-                                ;;
-      -i | --info)              run_mode="info";
-                                ;;
-      -k | --kill)              run_mode="kill";
-                                ;;
-      -m | --skip-load)         load_required_modeule="false";
-                                ;;
-      # Debugging options
-      --stderr)                 LOG_TO_STDERR="true";;
-      -v | --verbose)           LOG_LVL="1";
-                                log_info "Enable verbose logging";;
-      -h | --help )             display_usage;exit 0;;
-      * )                       log_error "Invalid argument(s). See usage below.";
-                                usage; exit 1;;
+    new) run_mode="new";
+        ((++exclusive_conflicts))
+      ;;
+    -r | --resolution)
+      shift
+      WM_RESOLUTION="${1}"
+      ;;
+    -g | --enable-vgl)
+      enable_vgl="true"
+      ;;
+    -a | --disable-autokill)
+      disable_autokill="true"
+      ;;
+    -i | --info)
+      run_mode="info"
+      ;;
+    -k | --kill)
+      run_mode="kill"
+      ;;
+    -m | --skip-load)
+      load_required_modeule="false"
+      ;;
+    # Debugging options
+    --stderr) LOG_TO_STDERR="true" ;;
+    -v | --verbose)
+      LOG_LVL="1"
+      log_info "Enable verbose logging"
+      ;;
+    -h | --help)
+      display_usage
+      exit 0
+      ;;
+    *)
+      log_error "Invalid argument(s). See usage below."
+      usage
+      exit 1
+      ;;
     esac
     shift
   done
@@ -456,12 +457,17 @@ function main()
 
   # Run
   case "${run_mode}" in
-    run)        run_vnc;;
-    kill)       vnc_kill;;
-    info)       display_info;exit $?;;
-    *)          log_error "Internal Error! Invalid mode!";exit 1;;
+  run) run_vnc ;;
+  kill) vnc_kill ;;
+  info)
+    display_info
+    exit $?
+    ;;
+  *)
+    log_error "Internal Error! Invalid mode!"
+    exit 1
+    ;;
   esac
-
 
 }
 
